### ISSUE TITLE
Feature request: Ignore defrecords

### ISSUE THREAD

**Issue by slipset** [borkdude/carve#1]
We (mis)use the component library in our system. This leads to a lot of `defrecords` which carve reports as being unused. It would be nice to have some way of having carve ignore the unused `defrecords`. Either by brute force ignore all defrecords, or maybe carve could know about the component-library?

**Comment by borkdude** [comment]
Fixed with `279fdd8a27b12b5bb1e20614cc23912e6fb8c465`

**Comment by slipset** [comment]
That was quick! Seems like `defprotocol` should be in that list as well?

**Comment by borkdude** [comment]
@slipset This now works after changing + upgrading clj-kondo.
