### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by AndreaCrotti** [borkdude/carve#11]
I ran the command `clojure -A:carve --opts '{:paths ["src" "test" "dev"] :interactive? false :aggressive? true}'` on one of my projects (and tried on a few other projects as well), but I get lots of false positives, many more things get deleted.

This is an example where the function deleted is just used straight after:

<img width="572" alt="Screenshot 2020-01-31 at 20 54 33" src="https://user-images.githubusercontent.com/53640/73573690-e6a53e80-446b-11ea-8cb7-b6d30f132c47.png">

**Comment by borkdude** [comment]
@AndreaCrotti Thanks. Is it possible for you to paste this code, so I can repro it more easily?

**Comment by borkdude** [comment]
@AndreaCrotti I think I already know what the issue is. With `:aggressive?` it runs carve multiple times, but it needs to know at least a few starting points that should never be removed.

E.g. if function a is the only function that is using function b and no-one is using function a, function b can also be removed, unless you mark function a as ignored.

**Comment by AndreaCrotti** [comment]
Ah right I see, I should try without aggressive. I guess tests should be handled differently ideally since a deftest is always used even with noone calling it

**Comment by borkdude** [comment]
Tests should already be ignored. When I test with this file:

```
(require '[clojure.test :as t])

(defn- private-fn [])

(t/deftest foo
  (private-fn))
```
it works like expected, but if I test with this file:

```
(require '[clojure.test :as t])

(defn- private-unused-fn [])
(defn- private-fn [])

(t/deftest foo
  (private-fn))
```

it only leaves:

```
(t/deftest foo
  (private-fn))
```

so that seems like a repro of what you were seeing. I'll take a look.

**Comment by borkdude** [comment]
@AndreaCrotti Pushed a fix. Can you try with the newest commit?

**Comment by AndreaCrotti** [comment]
Nice that issue is now solved,and tests are passing now so looking much better!
Thanks for the super fast fix
