### ISSUE TITLE
Options validation

### ISSUE THREAD

**Issue by AndreaCrotti** [borkdude/carve#12]
Would be nice to give a bit more feedback in case someone makes a silly mistake like

    clojure -A:carve --opts '{:paths [src]}'

instead of doing:

     clojure -A:carve --opts '{:paths ["src"]}'

At the moment it just runs without doing anything but also without giving any error.
I think in general if you don't pass any existing path (apart from the missing ") we should give an error since that's probably not what you wanted to do?

**Comment by borkdude** [comment]
PR welcome.

**Comment by AndreaCrotti** [comment]
👍 
is it ok to use spec to do the validation right?

**Comment by borkdude** [comment]
Assuming that we are not going to make a native executable from this project, then it should be OK. Otherwise it might lead to problems. But we'll figure that out later. Right now I'd say just go for it.
