### ISSUE TITLE
Always skip `-main`

### ISSUE THREAD

**Issue by AndreaCrotti** [borkdude/carve#13]
`-main` at the moment are always marked for deletion, would be good to ignore them by default since probably you don't want to delete them.

**Comment by borkdude** [comment]
Should probably be easy to add. PR welcome.

**Comment by AndreaCrotti** [comment]
Yeah I was checking where the skipping of deftest was done but it's in clj-kondo right?
Skipping the `-main` however should be done in this project then?

**Comment by borkdude** [comment]
All this logic is inside carve.
Skipping tests is done here: 

https://github.com/borkdude/carve/blob/33b2ece625fbdf4894415bd8b9dc68f49e3a9c7a/src/carve/impl.clj#L110

**Comment by AndreaCrotti** [comment]
Ah ok thanks I was looking for deftest and not ignore, should be easy then yeah

**Comment by AndreaCrotti** [comment]
This is now solved with https://github.com/borkdude/carve/pull/17
