### ISSUE TITLE
Rollback on signal interrupt

### ISSUE THREAD

**Issue by AndreaCrotti** [borkdude/carve#18]
I noticed that if you kill the process while you are doing a "carving session" all the changes you already accepted are not rolled back.

I guess there are pros and cons and with everything under revision control it should not matter so much, but maybe it should at least ask if you want to keep the changes or revert them?

**Comment by borkdude** [comment]
I don't think this complexity is worth implementing. If people don't trust what carve does, they should either use version control or the reporting option.
