### ISSUE TITLE
False positive with `:implements`

### ISSUE THREAD

**Issue by AndreaCrotti** [borkdude/carve#20]
This might be hard to implement, but I noticed that if you have a namespace like this

```(ns sample
  (:import (org.apache.kafka.streams.processor TimestampExtractor))
  (:gen-class
   :implements [org.apache.kafka.streams.processor.TimestampExtractor]))

(defn -extract [_ record previous]
  (do-something))
```

`-extract` would be deleted, even if it's actually used, and its definition has the side effect of implementing that interface.

**Comment by AndreaCrotti** [comment]
I guess we could ignore all the vars starting with  `-` maybe, assuming that's a well known convention for things that can have side effects on definition.

**Comment by borkdude** [comment]
That would also cover `-main` from the open PR.

**Comment by AndreaCrotti** [comment]
This is now solved with https://github.com/borkdude/carve/pull/17
(at least `-extract` would be ignored now)
