### ISSUE TITLE
Add output that is understandable by emacs

### ISSUE THREAD

**Issue by slipset** [borkdude/carve#3]
Emacs understands output on the form
`path/to/file.clj:161:32` where `161` is the line number and `32` is the column number (which can be elided. 
If carve could output this format, then carve could be run from within emacs (from `eshell` or something) and it could use the output to jump to the next unused symbol

**Comment by borkdude** [comment]
@slipset What about adding EDN output, so people can do whatever they want with this? You can then use this as a lib inside your own small deps.edn project to produce the output your need?

**Comment by borkdude** [comment]
We can rename the `:dry-run?` option to `:report`. When `true` it will behave the same as `dry-run?` but when given `{:format :edn}` it will print EDN, and for some other `:format` value we can print the Emacs format. But what would be a good name for that? `:lines`?
