### ISSUE TITLE
Binary releases?

### ISSUE THREAD

**Issue by AndreaCrotti** [borkdude/carve#35]
When running carve inside a limited network, it would be easier if there were binaries published automatically as it's done for clj-kondo.

The only way to make it work locally right now has been to clone carve locally and all it's dependencies, and use `:local/root` in my deps.edn to point to all the various deps.
This kind of works for dev but could be a bit painful to configure in the internal CI tool, any chance there could be binaries built with graalvm?

**Comment by borkdude** [comment]
Yes, good idea. I have a couple of `clojure` based GraalVM projects (rather than lein). One of them is https://github.com/borkdude/glam which supports binaries for all three major OSes (linux and mac via circleci, Windows via appveyor). We could just bring the config from that project over.

**Comment by borkdude** [comment]
There is now a carve binary release. See README.

**Comment by AndreaCrotti** [comment]
Great thanks @borkdude
