### ISSUE TITLE
Options from config file?

### ISSUE THREAD

**Issue by AndreaCrotti** [borkdude/carve#36]
When I pass many flags to carve, it gets a bit tricky to keep track of all the quotes and ().

Maybe if there was a flag `--opts-from` I could more simply have all the configuration in an end file and get read them from there?

**Comment by borkdude** [comment]
We could parse a file from `--opts` when:

- `opts` doesn't start with `{` 
- `(.exists (io/file opts)` returns true

**Comment by AndreaCrotti** [comment]
Yeah that would work and should not really break anything

**Comment by borkdude** [comment]
PR welcome.
