### ISSUE TITLE
Cleanup unused imports?

### ISSUE THREAD

**Issue by AndreaCrotti** [borkdude/carve#38]
A common issue when carving unused code is that there can be quite a few unused requires leftover that will break everything.
I was wondering if it was possible to carve them out as well, or potentially use another tool to delete all the unused imports before carving?

**Comment by borkdude** [comment]
I think this was already fixed by @russmatney in https://github.com/borkdude/carve/pull/33

**Comment by AndreaCrotti** [comment]
Ahh nice I just saw this problem a few days ago but I probably didn't have the latest and greatest version, thanks!
