### ISSUE TITLE
Confusing options merging

### ISSUE THREAD

**Issue by AndreaCrotti** [borkdude/carve#42]
If for example I have a config.edn file with `:paths ["src" "test"]`, and I pass options from CLI 
`:paths ["src"]` because I only want to see src now, the config from cli is not respected and still use `:paths ["src" "test"]`.

Other options get applied correctly instead, so it's quite confusing until you see how the code behaves, where collections are always merged.

IMHO it would be simpler and clearer to just ignore the default config file if you pass arguments from the CLI, since I would guess if you run it locally your really want to have certain options passed in.

**Comment by borkdude** [comment]
I agree, merging is probably confusing. Feel free to undo it.

**Comment by AndreaCrotti** [comment]
Ok great thanks
