### ISSUE TITLE
Preserve existing trailing newline when carving from the end of a file

### ISSUE THREAD

**Issue by guillaume** [borkdude/carve#46]
sample file for repro
[core_test.clj.zip](https://github.com/borkdude/carve/files/5851847/core_test.clj.zip)

yields only 7 lines after carve process. expectation is to preserve the newline in the file and thus get an empty line at line 8

@borkdude carve is a nice tool. we'd like to integrate it in CICD pipelines so it provides automatic fixes eventually

**Comment by borkdude** [comment]
PR welcome!

**Comment by AndreaCrotti** [comment]
https://juxt.pro/blog/carve could be helpful @guillaume .

And btw @borkdude another thing that is not preserved are windows newlines. 
I'd like to just get rid of them entirely but we on some projects we still have them and changing them it's just annoying in terms of git history.

**Comment by guillaume** [comment]
Do you think the fix belongs in carve or in rewrite-clj?

**Comment by borkdude** [comment]
Not sure. @lread, do you have an opinion on this?

**Comment by lread** [comment]
Rewite-clj preserving an existing newline at end of file seems reasonable to me. I just raised https://github.com/clj-commons/rewrite-clj/issues/121. @guillaume and others with an interest, happy to hear your feedback over there.

Rewrite-clj has a newline issue https://github.com/clj-commons/rewrite-clj/issues/93 which talks about @AndreaCrotti's OS specific newlines. I encourage folks to hop on over there to add to discussion.

**Comment by lread** [comment]
@guillaume, I am looking at this in https://github.com/clj-commons/rewrite-clj/issues/121, but always like to make sure I understand before I tackle an issue.

Here is what I tried to reproduce your issue using the carve binary on macOS:

```Shell
> mkdir carve-test
> cd carve-test
> curl -OL https://github.com/borkdude/carve/files/5851847/core_test.clj.zip
> unzip core_test.clj.zip 
> mkdir test
> cp core_test.clj test
> carve --opts '{:paths ["test"]}'  
> diff core_test.clj test/core_test.clj
```
I was expecting diff to report differences.

If I look at your repro file, `core_test.clj`, I'm thinking maybe it's not the one you intended to demonstrate the issue?
```Shell
> cat -e core_test.clj
(ns test-app.core-test$
  (:require [clojure.test :refer :all]$
            [test-app.core :refer :all]))$
$
(deftest a-test$
  (testing "FIXME, I fail."$
    (is (= 0 1))))$
```

When I first read this issue, I assumed something was being carved from the end of the file, and I'm guessing this is what you meant to show? So if we update `test/core_test.clj` to:

```Clojure
(ns test-app.core-test
  (:require [clojure.test :refer :all]
            [test-app.core :refer :all]))

(deftest a-test
  (testing "FIXME, I fail."
    (is (= 0 1))))


(defn i-am-unused[])



```

And then run:
```Shell
> carve --opts '{:paths ["test"] :interactive false}'
Carving test/core_test.clj

Found unused var:
------------------
(defn i-am-unused[])
------------------
Writing result to /Users/lee/Downloads/carve-test/test/core_test.clj
```

A diff shows what you were reporting:
```Shell
> diff core_test.clj test/core_test.clj 
7c7
<     (is (= 0 1))))
---
>     (is (= 0 1))))
\ No newline at end of file
```

That's it right? 

Now about the multiple newlines: I expect that when carving from the end of a file, you'd only expect to preserve one newline if there were multiple newlines.

Could the issue be re-titled to: "Preserve existing trailing newline when carving from the end of a file"?

Lemme know if my understanding is correct, thanks.

**Comment by guillaume** [comment]
Yes exactly it's only an issue if `carve` is carving something that's at the end of file. Otherwise it preserves it nicely

For the multiple newlines case, i don't have a strong opinion.

**Comment by lread** [comment]
Great @guillaume, thanks for confirming!
