### ISSUE TITLE
clj-kondo/config not working?

### ISSUE THREAD

**Issue by AndreaCrotti** [borkdude/carve#48]
I have a clj-kondo configuration in a project with something like
`:lint-as {bla-bla clojure.core/def...`

but if I run carve all the `bla-bla` do not get ignored.
So I tried to add also `bla-bla` the `:exclude` list and it's still same problem.

I then thought it was not reading the .clj-kondo/config.edn file and just pasted the whole thing in the `clj-kondo/config` keyword in .carve/config.edn, but it still didn't work.

Is the clj-kondo config maybe not being passed through?
From the code it looks like it should work so maybe something else is going on.

**Comment by borkdude** [comment]
@AndreaCrotti Can you create a repro?

**Comment by borkdude** [comment]
Closing for lack of repro
