### ISSUE TITLE
Clojure API

### ISSUE THREAD

**Issue by vemv** [borkdude/carve#55]
In a similar vein to https://github.com/clj-kondo/clj-kondo/issues/226, Carve could offer a clojure API.

Checking out https://github.com/borkdude/carve/blob/f499f65e36e02484609f01ce891f3c0207b24444/src/carve/main.clj#L64-L80, a few things stand out as not very api-ish:

* a `println`
* CLI option parsing
* Printing of reports (even when requesting edn) instead of returning edn directly

WDYT?

Thanks - V

**Comment by borkdude** [comment]
I think that makes sense.

**Comment by vemv** [comment]
PR welcome?

**Comment by borkdude** [comment]
Alright!
